/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeginnerFruitListRouteImport } from './routes/beginner/fruit-list'
import { Route as BeginnerCounterRouteImport } from './routes/beginner/counter'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnerFruitListRoute = BeginnerFruitListRouteImport.update({
  id: '/beginner/fruit-list',
  path: '/beginner/fruit-list',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnerCounterRoute = BeginnerCounterRouteImport.update({
  id: '/beginner/counter',
  path: '/beginner/counter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/beginner/counter': typeof BeginnerCounterRoute
  '/beginner/fruit-list': typeof BeginnerFruitListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/beginner/counter': typeof BeginnerCounterRoute
  '/beginner/fruit-list': typeof BeginnerFruitListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/beginner/counter': typeof BeginnerCounterRoute
  '/beginner/fruit-list': typeof BeginnerFruitListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test' | '/beginner/counter' | '/beginner/fruit-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test' | '/beginner/counter' | '/beginner/fruit-list'
  id: '__root__' | '/' | '/test' | '/beginner/counter' | '/beginner/fruit-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  BeginnerCounterRoute: typeof BeginnerCounterRoute
  BeginnerFruitListRoute: typeof BeginnerFruitListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginner/fruit-list': {
      id: '/beginner/fruit-list'
      path: '/beginner/fruit-list'
      fullPath: '/beginner/fruit-list'
      preLoaderRoute: typeof BeginnerFruitListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginner/counter': {
      id: '/beginner/counter'
      path: '/beginner/counter'
      fullPath: '/beginner/counter'
      preLoaderRoute: typeof BeginnerCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  BeginnerCounterRoute: BeginnerCounterRoute,
  BeginnerFruitListRoute: BeginnerFruitListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
